### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KaUwu** [nukebot/discord-nuke-bot#24]
Its not workin for me. Idk why. when i type the cmd then its crashes with this error message:

Ignoring exception in command rape:
Traceback (most recent call last):
  File "C:\Users\Kaszben\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Kaszben\Desktop\Nuking-Discord-Server-Bot-Nuke-Bot-2.4.0\nuke\main.py", line 120, in rape
    for channel in list(ctx.message.server.channels):
AttributeError: 'Message' object has no attribute 'server'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kaszben\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Kaszben\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Kaszben\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Message' object has no attribute 'server'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020AE3BB6050>
Traceback (most recent call last):
  File "C:\Users\Kaszben\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\Kaszben\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\Kaszben\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "C:\Users\Kaszben\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

**Comment by jazthelinuxgyt** [comment]
This is because its poorly made. Use a paid one or reputable. Dont use grabbers. Always check all scripts.
